### ISSUE TITLE
How to name the AnalysisCuts folders with vertex selection cuts on/off as an option ?  

### ISSUE THREAD

**Issue by pkotamnives** [DisplacedVertices/cmssw-usercode#14]
https://github.com/DisplacedVertices/cmssw-usercode/blob/e0bd431632f8a9488c48cbe1faf657a94e7e6f1f/MFVNeutralino/test/histos.py#L74

**Comment by jreic** [comment]
I think `mfvAnalysisCutsPreSelEvtFiltVtxSel` should just be `mfvAnalysisCutsPreSelEvtFilt`. 

There is no vtx selection being done in
https://github.com/DisplacedVertices/cmssw-usercode/blob/e0bd431632f8a9488c48cbe1faf657a94e7e6f1f/MFVNeutralino/test/histos.py#L28

so the vtx selection comes from
https://github.com/DisplacedVertices/cmssw-usercode/blob/e0bd431632f8a9488c48cbe1faf657a94e7e6f1f/MFVNeutralino/test/histos.py#L69

which is the second half of the line
`process.EX1pPreSelEvtFiltVtxSel     = cms.Path(common * process.mfvAnalysisCutsPreSelEvtFiltVtxSel                                              * process.EX1mfvVertexHistosPreSelEvtFiltVtxSel)`

Do you agree? We can also remove some of the unnecessary spaces in the `process.EX1pPreSelEvtFiltVtxSel` line.

**Comment by pkotamnives** [comment]
Okay! if the selection is always off.
